docker and demo

diff --git a/.pkg/docker-build b/.pkg/docker-build
--- a/.pkg/docker-build
+++ b/.pkg/docker-build
@@ -1,10 +1,16 @@
 #!/bin/bash
 
-vers=$(date +%y%m.%d%H%M)
 if [ $1 ]; then
 	images="$@"
 else
-	images="tools engine demo"
+	images="tools engine"
+fi
+
+if [ -f actions.json ]; then
+	cd ..
+elif [ ! -f .pkg/actions.json ]; then
+	echo "Unable to find .pkg/Dockerfile.*"
+	exit 1
 fi
 
 for type in $images; do
diff --git a/.pkg/docker-push b/.pkg/docker-push
--- a/.pkg/docker-push
+++ b/.pkg/docker-push
@@ -2,8 +2,22 @@
 
 vers=$(date +%y%m.%d%H%M)
 
-for type in tools engine demo; do
+if [ -f actions.json ]; then
+	cd ..
+elif [ ! -f .pkg/actions.json ]; then
+	echo "Unable to find .pkg/Dockerfile.*"
+	exit 1
+fi
+
+if [ $1 ]; then
+	images="$@"
+else
+	images="tools engine"
+fi
+
+for type in $images; do
 	docker tag reflexsc/$type:latest reflexsc/$type:$vers
-	docker push reflexsc/$type:latest reflexsc/$type:$vers
+	docker push reflexsc/$type:latest
+	docker push reflexsc/$type:$vers
 done
 
